name = "TopOptLevelSet"
uuid = "6bdd9269-80dc-4ea4-ab9e-470a0531a81b"
authors = ["Mohamed Tarek <mohamed82008@gmail.com> and contributors"]
version = "0.0.1"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
